#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Generate one icon RRO per app from the design export (icons/apps/<name>/*.xml)
# into vendor/budikos/overlay/icons, plus the Android.bp modules and icons.mk.
# Usage: tools/gen-icon-overlays.sh <design export dir>
set -euo pipefail
SRC="${1:?usage: $0 <design export dir>}/icons/apps"
V="$(dirname "$(dirname "$(readlink -f "$0")")")/vendor/budikos"
D=$V/overlay/icons
rm -rf "$D"; mkdir -p "$D"
BP=$V/icons.bp.tmp; : > "$BP"; MODS=()
# name|package|resource type|resource name
while IFS='|' read -r n pkg t r; do
  m="BudikIcon_${n}"; o="$D/$n"
  mkdir -p "$o/res/drawable" "$o/res/${t}-anydpi-v26"
  for l in background foreground monochrome; do
    cp "$SRC/$n/$l.xml" "$o/res/drawable/ic_launcher_${n}_$l.xml"
  done
  cp "$SRC/$n/ic_launcher.xml" "$o/res/${t}-anydpi-v26/$r.xml"
  cat > "$o/AndroidManifest.xml" <<M
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.budikos.overlay.icon.$n">
    <overlay android:targetPackage="$pkg" android:isStatic="true" android:priority="900" />
    <application android:hasCode="false" />
</manifest>
M
  cat >> "$BP" <<B

runtime_resource_overlay {
    name: "$m",
    product_specific: true,
    manifest: "overlay/icons/$n/AndroidManifest.xml",
    resource_dirs: ["overlay/icons/$n/res"],
}
B
  MODS+=("$m")
done <<'L'
telefon|com.android.dialer|mipmap|ic_launcher
kontakty|com.android.contacts|mipmap|ic_launcher
zpravy|com.android.messaging|mipmap|ic_launcher
nastaveni|com.android.settings|mipmap|ic_launcher
soubory|com.android.documentsui|mipmap|ic_launcher
obchod|app.grapheneos.apps|mipmap|ic_launcher
prohlizec|org.chromium.webview_shell|drawable|ic_launcher
fotoaparat|app.grapheneos.camera|mipmap|ic_launcher
galerie|com.android.gallery3d|mipmap|ic_launcher
hodiny|com.android.deskclock|mipmap|ic_launcher
kalkulacka|com.android.calculator2|mipmap|ic_launcher
kalendar|com.android.calendar|mipmap|ic_launcher_calendar
L
# Android.bp = static overlays + generated icon overlays
sed -i '/^\/\/ --- generated icon overlays/,$d' "$V/Android.bp"
{ echo "// --- generated icon overlays (tools/gen-icon-overlays.sh), do not edit below"; cat "$BP"; } >> "$V/Android.bp"
rm "$BP"
{ echo "# generated by tools/gen-icon-overlays.sh"; echo "PRODUCT_PACKAGES += \\"; for m in "${MODS[@]}"; do echo "    $m \\"; done; echo; } > "$V/icons.mk"
echo "OK ${#MODS[@]} overlays"
